### ISSUE TITLE
Launch-File für turtlebot designen. Ja das andere, welches auf dem Bot ist habe ich gelöscht

### ISSUE THREAD

**Issue by Lorenzuser** [Lorenzuser/HomeDirect_ws#16]

**Comment by Al3xAda** [comment]
Bin mir allgemein nicht ganz sicher wie ich die Laucnh File machen soll. Momentan kann ich sie gar nicht starten. Außerdem mach ich mir etwas sorgen beim Herumspielen mit `colcon build` etwas kaputt zu machen .

**Comment by Lorenzuser** [comment]
Wir haben das launch_File heute noch geschrieben. Allles funktioniert.

![Image](https://github.com/Lorenzuser/HomeDirect_ws/assets/93797283/0bb761d5-cd61-4b90-ac51-eec1ab3ee5ff)
