### ISSUE TITLE
rfid_publisher mit ˋbringupˋ starten lassen

### ISSUE THREAD

**Issue by Al3xAda** [Lorenzuser/HomeDirect_ws#3]
Link zur executable und dem Package herstellen

**Comment by Al3xAda** [comment]
Idee für Änderung von `/turtlebot3_bringup/launch/robot.launch.py`


![Image](https://github.com/Lorenzuser/HomeDirect_ws/assets/123410382/c6b0e7ce-f5aa-4de1-bb81-37e53716f9ec)

**Comment by Al3xAda** [comment]
weitere Idee



![Image](https://github.com/Lorenzuser/HomeDirect_ws/assets/123410382/d3a87b7e-55d6-46cb-bd2d-703a33d44c42)

**Comment by Al3xAda** [comment]
Idee:


![Image](https://github.com/Lorenzuser/HomeDirect_ws/assets/123410382/263b5c38-ec01-4e7b-9915-4319da3c0fb3)

**Comment by Al3xAda** [comment]
Es könnte jedoch auch besser sein einfach allgemein eine ganz neue launch-file zu machen die alles relevante startet  

- Navigation
- RFID Leser
- ursprüngliches Bringup

**Comment by Lorenzuser** [comment]
Wir müssen keine Navigation vom Bot starten nur Bringup und RFID bis jetzt. Kann man vielleicht ein Launch File, durch ein Launch File starten? Vielleicht auf ähnliche Weise wie eine Node, das könnte alles einfacher machen.

**Comment by Al3xAda** [comment]
Ja, das ist im Prinzip das Ziel bei Issue #6
Ich meine ich sollte Die neueste Version der `homedirect_bringup` file bereits commited haben

**Comment by Al3xAda** [comment]
Test benötigt
