### ISSUE TITLE
Launch File für den Roboter mit allen Relevanten Prozessen erstellen

### ISSUE THREAD

**Issue by Al3xAda** [Lorenzuser/HomeDirect_ws#6]

**Comment by Al3xAda** [comment]
![Image](https://github.com/Lorenzuser/HomeDirect_ws/assets/123410382/bea2d87b-e925-466a-8e5f-3800c0bbf922)

@Lorenzuser Ich weiß nicht genau ob `nav_main` oder `controller_main` auf dem Roboter gestartet werden sollte

**Comment by Lorenzuser** [comment]
Kind of doesnt matter. Ich habe einfach zwei Programme gemacht um verschiedene Code abzuspeichern. Da ich "ros2 run" benutzt habe, war das nicht wichtig. Füge einfach eins der beiden hinzu, ich passe das dann an, wenn ich weitere Erkenntnis habe.

**Comment by Al3xAda** [comment]
~~muss noch getestet werden aber fertig~~

neue programme fehlen
